### ISSUE TITLE
VIP Server Issue

### ISSUE THREAD

**Issue by SavageKiller13** [MinersHavenPlus/Miners-Haven-Plus#19]
Whenever I try to load into a VIP server the server loads but the spawning outside of the map issue occurs. It's not a gamebreaking bug but an annoying one nonetheless.

**Comment by INWNMTheBossM** [comment]
These are the errors coming up when playing on a VIP server.

**https://gyazo.com/1ceffee980c9a292dcbb85a234b569d1**
**https://gyazo.com/f1460bfdfb186b2273cb56ba7098c1e0**
