### ISSUE TITLE
Ore's aren't processed

### ISSUE THREAD

**Issue by squiddy1** [MinersHavenPlus/Miners-Haven-Plus#31]
**Bug:** Sometimes, ores aren't processed by the furnace. Similar to the teleporter bug, they just sit there.
**What I was doing before:** I was trying to get $inf by looping Hades' Fang & Stardust Mines.
(I think there's an issue with Hades' Fang and processing ores through furnaces)

**Today (7/2/2020):** 
https://prnt.sc/tap3to
https://prnt.sc/tap40d
https://prnt.sc/tap31w

**Yesterday (7/1/2020):**
https://prnt.sc/t9k3fe
https://prnt.sc/t9jz2f
https://prnt.sc/t8xpzf

**Comment by bryce-happel-walton** [comment]
I will look into this. By the way your first screenshot shows warnings made by Roblox UI, not MHP
