### ISSUE TITLE
Shards reset when I rejoin

### ISSUE THREAD

**Issue by OnlyMinersHaven1** [MinersHavenPlus/Miners-Haven-Plus#36]
I keep having this issue where I can join with 600 shards and then leave with lets say 20k. When I join later on im back to 600 shards and then I just feel like it wasn't worth grinding those shards because they keep ressetting.

I don't know how I get a pic of the console log in here.

**Comment by bryce-happel-walton** [comment]
Could you provide more details please? Since this is a server issue the console log will not be necessary. Are you leaving and joining in quick succession, are you leaving immediately after rebirthing etc... I have not been able to reproduce this bug, and the code surrounding the Shards is solid.
