### ISSUE TITLE
set ups broken after reset

### ISSUE THREAD

**Issue by aXxG3TR3KTxX591** [MinersHavenPlus/Miners-Haven-Plus#40]
![Roblox 7_10_2020 5_57_57 PM](https://user-images.githubusercontent.com/45795606/87206119-0a03cd80-c2d7-11ea-9184-3a48b3fdc033.png)

**Comment by MrTaco9001** [comment]
For one thing this is not a bug report, it is a screenshot. And for another, the layouts still work completely fine. The UI is not updated.
