### ISSUE TITLE
Can’t place anything after 2 seconds

### ISSUE THREAD

**Issue by iOperion** [MinersHavenPlus/Miners-Haven-Plus#8]
It is not just me it is a lot of other people. I have tried other accounts and tried switching my internet, it would not work. It will be blue when I pull it out of the inv but then when I move the object even a couple spaces to get it to place where I want it to it turns red and goes back into my inv when I try to place it. I am very new, but I am verified and I’ve done everything needed to play, it just ruins the whole experience for me.

**Comment by bryce-happel-walton** [comment]
We are aware of the issue and unfortunately since I didn’t write the script and it’s several thousand lines long it takes a while to debug. TLDR we’re working on it!
